version: "3.8"

services:
  lena-session-0:
    image: lenacloud/lena-session:1.3.1.0_6-centos7-jdk8-openjdk
    networks:
      lena-net:
        aliases:
        - session-0.example.local
    environment:
      LENA_MANAGER_ADDRESS: "lena-manager.example.local:7700"
      LENA_MANAGER_MONITORING_PORT: "16100"
      LENA_CONFIG_TEMPLATE_ID: "session-cluster"
      LENA_SESSION_0_ADDRESS: "session-0.example.local:5180"
      LENA_SESSION_1_ADDRESS: "session-1.example.local:5180"
      LENA_SECONDARY_SESSION_NO: 1
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: "sh /usr/local/lena/servers/sessionServer/health.sh"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  lena-session-1:
    image: lenacloud/lena-session:1.3.1.0_6-centos7-jdk8-openjdk
    networks:
      lena-net:
        aliases:
        - session-1.example.local
    environment:
      LENA_MANAGER_ADDRESS: "lena-manager.example.local:7700"
      LENA_MANAGER_MONITORING_PORT: "16100"
      LENA_CONFIG_TEMPLATE_ID: "session-cluster"
      LENA_SESSION_0_ADDRESS: "session-0.example.local:5180"
      LENA_SESSION_1_ADDRESS: "session-1.example.local:5180"
      LENA_SECONDARY_SESSION_NO: 0
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: "sh /usr/local/lena/servers/sessionServer/health.sh"
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
