version: "3.8"

services:
  lena-web-cluster:
    image: lenacloud/lena-web:1.3.1.0_6-centos7-jdk8-openjdk
    networks:
      lena-net:
        aliases:
        - web-cluster.example.local
    ports:
    - target: 7180
      published: 7180
      protocol: tcp
      mode: ingress
    environment:
      LENA_MANAGER_ADDRESS: "lena-manager.example.local:7700"
      LENA_MANAGER_MONITORING_PORT: "16100"
      LENA_MANAGER_KEY: "C9PYwcu%2FDcB12IyhTrD63o2mXtnCWqV0dvnhunznedBnpRUgjVr6QeLA9zvReQqWMzbgyIHNVajoSvSuE0jANQ%3D%3D"
      LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
      LENA_CONFIG_TEMPLATE_ID: "web-cluster"
      LENA_LICENSE_DOWNLOAD_URL: "manager"
      LENA_CONTRACT_CODE: "vvW7ebNFVjDdtasuvF1utQ=="
      LENA_AGENT_RUN: "Y"
    deploy:
      mode: replicated
      replicas: 2
    healthcheck:
      test: "curl -f http://localhost:7180/index.html"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s