version: "3.8"
services:
  lena-manager:
    image: lenacloud/lena-manager:1.3.1.0_6-centos7-jdk8-openjdk
    networks:
      lena-net:
        aliases:
        - "lena-manager.example.local"
    ports:
    - target: 7700
      published: 7700
      protocol: tcp
      mode: host
    environment:
      LENA_MANAGER_DOMAIN_ENABLED: "Y"
      LENA_MANAGER_ADDRESS: "lena-manager.example.local:7700"
      LENA_MANAGER_MONITORING_PORT: "16100"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    volumes:
    - lena-manager-repository:/usr/local/lena/repository
    healthcheck:
      test: "curl -f http://localhost:7700/lena"
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
volumes:
  lena-manager-repository:
    driver: local
    driver_opts:
      type: "nfs"
      o: "nfsvers=4.1,addr=${FILE_STORAGE_ADDRESS}"
      device: "${FILE_STORAGE_ADDRESS}:/example/lena-manager-repository"
