version: "3.8"

services:
  lena-was-cluster:
    image: lenacloud/lena-cluster:1.3.1.0_6-centos7-jdk8-openjdk
    networks:
      lena-net:
        aliases:
        - was-cluster.example.local
    ports:
    - target: 8180
      published: 8180
      protocol: tcp
      mode: ingress
    environment:
      LENA_MANAGER_ADDRESS: "lena-manager.example.local:7700"
      LENA_MANAGER_MONITORING_PORT: "16100"
      LENA_MANAGER_KEY: "C9PYwcu%2FDcB12IyhTrD63o2mXtnCWqV0dvnhunznedBnpRUgjVr6QeLA9zvReQqWMzbgyIHNVajoSvSuE0jANQ%3D%3D"
      LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
      LENA_CONFIG_TEMPLATE_ID: "was-cluster"
      LENA_LICENSE_DOWNLOAD_URL: "manager"
      LENA_CONTRACT_CODE: "vvW7ebNFVjDdtasuvF1utQ=="
      JAVA_DOMAIN_CACHE_TTL: "3"
    deploy:
      mode: replicated
      replicas: 3
    healthcheck:
      test: "curl -f http://localhost:8180/index.jsp"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s