---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      name: was-cluster
  replicas: 3
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        name: was-cluster
    spec:
      containers:
      - name: was-cluster
        image: lenacloud/lena-cluster:1.3.1.0-centos7-jdk8-openjdk
        livenessProbe:
          httpGet:
            path: /index.jsp
            port: 8180
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /index.jsp
            port: 8180
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
        - containerPort: 8180
        envFrom:
        - configMapRef:
            name: was-cluster-config
      terminationGracePeriodSeconds: 10

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: was-cluster-config
  namespace: default
data:
  LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_MANAGER_MONITORING_PORT: "16100"
  LENA_MANAGER_KEY: "p5IsZQME5ORlIf2hbi0ooyXzpHD7Tz6gjc9yYySyU7VxsBD508y0O%2BBa6jiC4aiHLdr%2BXhCYzSNNxWkkKNM1ow%3D%3D"
  LENA_CONFIG_TEMPLATE_DOWNLOAD: "Y"
  LENA_CONFIG_TEMPLATE_ID: "was-cluster"
  LENA_LICENSE_DOWNLOAD_URL: "manager"
  LENA_CONTRACT_CODE: "a4ujg2LVNL9NuP3IMKTkug=="
  JAVA_DOMAIN_CACHE_TTL: "3"
  LENA_AGENT_RUN: "Y"
  LENA_HEALTH_CHECK: "Y"
  LENA_HEALTH_CHECK_INITIAL_DELAY_MILLISEC: "60000"
  LENA_HEALTH_CHECK_TIMEOUT_MILLISEC: "5000"
  LENA_HEALTH_CHECK_FAILURE_THRESHOLD: "5"
  


