---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-external
  namespace: default
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    name: web-cluster
  ports:
  - port: 7180
    targetPort: 7180
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: web-cluster-internal
  namespace: default
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-type: nlb
#    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    name: web-cluster
  ports:
  - port: 7180
    targetPort: 7180
  type: LoadBalancer