---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lena-manager
  namespace: default
spec:
  selector:
    matchLabels:
      name: lena-manager
  serviceName: lena-manager
  replicas: 1
  template:
    metadata:
      labels:
        name: lena-manager
    spec:
      containers:
      - name: lena-manager
        image: lenacloud/lena-manager:1.3.1.0_6-centos7-jdk8-openjdk
        imagePullPolicy: Always
        ports:
        - containerPort: 7700
        livenessProbe:
          httpGet:
            path: /lena
            port: 7700
          initialDelaySeconds: 30
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: lena-manager-config
        volumeMounts:
        - name: lena-manager-repository
          mountPath: /usr/local/lena/repository
      volumes:
        - name: lena-manager-repository
          nfs:
            server: fs-8a5d26eb.efs.ap-northeast-2.amazonaws.com
            path: /example/lena-manager-repository
      terminationGracePeriodSeconds: 0
      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lena-manager-config
  namespace: default
data:
  LENA_MANAGER_DOMAIN_ENABLED: "Y"
  LENA_MANAGER_ADDRESS: "lena-manager.default.svc.cluster.local:7700"
  LENA_MANAGER_MONITORING_PORT: "16100"
  
---
apiVersion: v1
kind: Service
metadata:
  name: lena-manager
  namespace: default
spec:
  selector:
    name: lena-manager
  ports:
  - name: service
    protocol: TCP
    port: 7700
    targetPort: 7700
  - name: monitoring
    protocol: UDP
    port: 16100
  type: NodePort
