---
apiVersion: v1
kind: PersistentVolumeClaim              
metadata:
  name: lena-manager-repository
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: regionalpd-ssd